#!/bin/sh
WID=""
CONV="bmp"
EXT="bmp"
IMPORT=${IMPORT-import}
if [ -z "$1" ];
then
	WID="`xwininfo | grep Window\ id | cut -d' ' -f 4`"
else
	WID="$1"
fi

FN=""
TMP=${TMP-"/tmp"}
FILE=""

while true; do
	FN="`date +z%YD%jT%H%M%S`"
	if [ ! -e "$FN" ]; then
		break;
	else 
		unset FN
	fi
done;
[ -z "$FN" ] && exit 2
FILE="$TMP/$FN/$FN.$EXT"

mkdir -p "$TMP/$FN"
$IMPORT -window $WID "$CONV:$FILE"
if [ ! -e "$FILE" ] && [ "root" != "$WID" ];
then
	$IMPORT -window root "$CONV:$FILE"
fi

echo $$ > "${TMP}/${USER}_$$.unlock"
if [ -e "$FILE" ];
then
	$SCR_TERM -e "__screenshot \"$FILE\" \"$FN\" \"$CONV\" 2>$TMP/$FN/stderr"
	if [ -r "$TMP/$FN/stderr" ];
	then
		[ `stat -c %s $TMP/$FN/stderr` -ne 0 ] &&\
			$SCR_TERM -e "sh -c 'cat $TMP/$FN/stderr | less'"
	fi
fi
rm -rf "$TMP/$FN" >/dev/null 2>&1
rm -rf "${TMP}/${USER}_${q}.unlock" >/dev/null 2>&1

